# Generated by Django 4.0.6 on 2022-08-25 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trail_Checkpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail')),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.CharField(max_length=100)),
                ('warning_rating', models.IntegerField()),
                ('trail_checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail_checkpoints')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('emergency_contact_number', models.IntegerField()),
                ('address', models.TextField()),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.status')),
                ('current_trail_checkpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail_checkpoints')),
            ],
        ),
    ]
