# Generated by Django 4.0.6 on 2022-09-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='person_id',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.person'),
            preserve_default=False,
        ),
    ]
