# Generated by Django 4.0.6 on 2022-07-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('emergency_contact_number', models.IntegerField()),
                ('address', models.TextField()),
                ('departure', models.DateTimeField()),
                ('eta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('person_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=100)),
                ('trail_checkpoint', models.IntegerField()),
                ('trail_length', models.IntegerField()),
                ('trail_warnings', models.CharField(max_length=100)),
                ('person_trail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='authority',
            name='last_known_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail'),
        ),
    ]
