# Generated by Django 4.0.6 on 2022-08-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_status',
            new_name='current_status',
        ),
    ]
