# Generated by Django 4.0.6 on 2022-09-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='current_status',
        ),
        migrations.AddField(
            model_name='person',
            name='current_trail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail'),
        ),
        migrations.AddField(
            model_name='person',
            name='statuses',
            field=models.ManyToManyField(blank=True, null=True, to='hikeme_app.status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_trail_checkpoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail_checkpoints'),
        ),
    ]
