# Generated by Django 4.0.6 on 2022-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0002_remove_person_current_status_person_current_trail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trail_Checkpoints',
            new_name='Trail_Checkpoint',
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('relevant_trail', models.ManyToManyField(to='hikeme_app.trail')),
                ('relevant_trail_checkpoint', models.ManyToManyField(to='hikeme_app.trail_checkpoint')),
            ],
        ),
    ]
