# Generated by Django 4.0.6 on 2022-09-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0002_warning_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warning',
            old_name='person_id',
            new_name='person',
        ),
    ]
