# Generated by Django 4.0.6 on 2022-09-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0003_rename_trail_checkpoints_trail_checkpoint_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_checkin', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.person')),
                ('trail_checkpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail_checkpoint')),
            ],
        ),
    ]
