# Generated by Django 4.0.6 on 2022-09-14 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hikeme_app', '0004_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='warning',
            name='trail_checkpoint',
        ),
        migrations.AddField(
            model_name='warning',
            name='trail_checkpoint',
            field=models.ManyToManyField(to='hikeme_app.trail_checkpoint'),
        ),
    ]
