# Generated by Django 4.1.1 on 2022-09-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0006_warning_trail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.person')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail')),
            ],
        ),
    ]
