# Generated by Django 4.1.1 on 2022-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0007_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date_posted',
            field=models.DateTimeField(default='2007-01-01 10:00:00'),
            preserve_default=False,
        ),
    ]
