# Generated by Django 4.1.1 on 2023-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0008_status_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warning',
            old_name='person',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='current_trail',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='statuses',
        ),
        migrations.RemoveField(
            model_name='warning',
            name='trail',
        ),
        migrations.AddField(
            model_name='warning',
            name='checked_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
