# Generated by Django 4.1.1 on 2023-02-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0009_rename_person_warning_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warning',
            old_name='user',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='warning',
            name='checked_by_staff',
        ),
        migrations.AddField(
            model_name='person',
            name='current_trail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Cade', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Clark', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='statuses',
            field=models.ManyToManyField(blank=True, null=True, to='hikeme_app.status'),
        ),
        migrations.AddField(
            model_name='warning',
            name='trail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('relevant_trail', models.ManyToManyField(to='hikeme_app.trail')),
                ('relevant_trail_checkpoint', models.ManyToManyField(to='hikeme_app.trail_checkpoint')),
            ],
        ),
    ]
