# Generated by Django 4.1.1 on 2023-02-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0010_rename_user_warning_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='statuses',
        ),
        migrations.AddField(
            model_name='status',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.person'),
            preserve_default=False,
        ),
    ]
