# Generated by Django 4.1.1 on 2023-03-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikeme_app', '0013_hike_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='trail',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hikeme_app.trail'),
            preserve_default=False,
        ),
    ]
